home:
   path: /
   controller: App\Controller\HomeController::home

galerie:
    path: /galerie
    controller: App\Controller\HomeController::galerie
    methods: GET

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }